name: Good Grinds
favicon: null
layout_spectrum: 0
typography_spectrum: 0.67652
title: Good Grinds
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0d0d'
    - '#98aebc'
    - '#5c171a'
    - '#56483d'
  brandStrength: 0.6372702054213732
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
