title: Good Grinds
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#ffffff'
    - '#0d0d0d'
    - '#98aebc'
    - '#5c171a'
    - '#56483d'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Good Grinds
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4148936
layout_spectrum: 1
